# Last edited: 2026-01-29 (partially generated by AI)
import json
import tempfile
from pathlib import Path

from models.file_manager import FileManager


REAPER_TEMPLATE = Path("~/.config/REAPER/ProjectTemplates/default.RPP").expanduser()


def write_metadata(fm: FileManager, kind: str, slug: Path) -> None:
    metadata = fm.create_metadata(kind, slug)
    if metadata is None:
        print(f"Metadata creation failed for {slug}")
        return
    with open(slug / ".metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="mdo_test_") as tmp:
        root = Path(tmp)
        (root / "songs").mkdir()
        (root / "albums").mkdir()

        fm = FileManager(root)
        song_title = "test-song"
        song_root = fm.create_song(song_title, ["lyrics"])
        if not song_root:
            print("Song creation failed")
            return

        write_metadata(fm, "song", song_root)

        lyric_path = fm.create_lyrics(song_root, song_title)
        print("Lyric created:", lyric_path)

        if REAPER_TEMPLATE.exists():
            project_path = fm.create_project(song_root, song_title)
            print("Project created:", project_path)
        else:
            print("Project template missing, skipping project creation:", REAPER_TEMPLATE)

        fm2 = FileManager(root)
        album_title = "test-album"
        album_root = fm2.create_album(album_title, [song_root.name])
        print("Album created:", album_root)
        album_root_dup = fm2.create_album(album_title, [song_root.name])
        print("Album duplicate rejected:", album_root_dup is None)

        if album_root:
            link_path = album_root / "songs" / song_root.name
            print("Album song link exists:", link_path.exists())
            print("Album song link is symlink:", link_path.is_symlink())

        print("Song metadata exists:", (song_root / ".metadata.json").exists())
        if album_root:
            print("Album metadata exists:", (album_root / ".metadata.json").exists())

        song_root_dup = fm.create_song(song_title, ["lyrics"])
        print("Song duplicate rejected:", song_root_dup is None)


if __name__ == "__main__":
    main()
